services:
    laravel.test:
        build:
            context: './docker/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            - '${REVERB_PORT:-8080}:${REVERB_PORT:-8080}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - redis

    redis:
        image: 'redis:alpine'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    mosquitto:
        image: eclipse-mosquitto:2
        ports:
            - '${MQTT_PORT:-1883}:1883'
            - '9001:9001'
        volumes:
            - './mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf'
            - './mosquitto/config/passwd:/mosquitto/config/passwd'
            - 'sail-mosquitto-data:/mosquitto/data'
            - 'sail-mosquitto-log:/mosquitto/log'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
    sail-mosquitto-data:
        driver: local
    sail-mosquitto-log:
        driver: local
