services:
    portatec:
        image: portatec
        build:
            context: ./
            dockerfile: ./docker/prod/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            # - '${APP_PORT:-80}:80'
            # - '${HTTPS_PORT:-443}:443'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            # - '${REVERB_PORT:-8080}:${REVERB_PORT:-8080}'
        environment:
            WWWUSER: '${WWWUSER}'
        volumes:
            - './.env:/var/www/.env'
            - './database.sqlite:/var/www/database/database.sqlite'
            - './storage:/var/www/storage'
        networks:
            - medeirostec-network
        depends_on:
            - redis
        restart: always


    redis:
        image: 'redis:alpine'
        volumes:
            - 'portatec-redis:/data'
        networks:
            - medeirostec-network
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
        restart: always

    mosquitto:
      image: eclipse-mosquitto
      container_name: mosquitto
      restart: always
      ports:
          - "1883:1883"
          - "9001:9001"
      volumes:
          - ./mosquitto/auth:/etc/mosquitto
          - ./mosquitto/data:/mosquitto/data
          - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      networks:
          - medeirostec-network

networks:
  medeirostec-network:
      external: true
      name: medeirostec-network
      driver: bridge

volumes:
    portatec-redis:
        driver: local
